// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7YViqy8QQIcIqixZkFBeI4vSx7QLuFt8',
    appId: '1:812829259045:web:32ade77225c123b26216cc',
    messagingSenderId: '812829259045',
    projectId: 'shipment-app-881a2',
    authDomain: 'shipment-app-881a2.firebaseapp.com',
    storageBucket: 'shipment-app-881a2.firebasestorage.app',
    measurementId: 'G-JZZP5BNPSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdTPxiKzylr_lNuvqkecnNSnON-hiWXwQ',
    appId: '1:812829259045:android:86ef4ec316a887296216cc',
    messagingSenderId: '812829259045',
    projectId: 'shipment-app-881a2',
    storageBucket: 'shipment-app-881a2.firebasestorage.app',
  );
}
